// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Xh7WPLgpxm-_7ahXXCFwFkPmLUJIh38',
    appId: '1:580307087717:web:aa1df2f96e30afba59318c',
    messagingSenderId: '580307087717',
    projectId: 'due-manager-10dd1',
    authDomain: 'due-manager-10dd1.firebaseapp.com',
    storageBucket: 'due-manager-10dd1.firebasestorage.app',
    measurementId: 'G-9CLPW274DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDArDzngTdgZH25T7gBkSvCzLe5l6Prr-w',
    appId: '1:580307087717:android:e2e8e146ae0019ef59318c',
    messagingSenderId: '580307087717',
    projectId: 'due-manager-10dd1',
    storageBucket: 'due-manager-10dd1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Xh7WPLgpxm-_7ahXXCFwFkPmLUJIh38',
    appId: '1:580307087717:web:e528cfaad9f5788f59318c',
    messagingSenderId: '580307087717',
    projectId: 'due-manager-10dd1',
    authDomain: 'due-manager-10dd1.firebaseapp.com',
    storageBucket: 'due-manager-10dd1.firebasestorage.app',
    measurementId: 'G-EYH9E0BNFY',
  );
}
